### ISSUE TITLE
Update docs to mention Substr type in more places, cut 0.2.2

### ISSUE THREAD

**Issue by thomcc** [thomcc/arcstr#13]
Didn't do this in #12 because I'd rather let it stew in the ol' slowcooker for a bit. Maybe play with it in another project in case it's one of those "this api certainly exists but sure as hell feels like no human ever used it" cases I hate so much.

**Comment by jyn514** [comment]
Interested in making a PR switching `saltwater` to ArcStr? 😉

**Comment by thomcc** [comment]
i'll give it a stab later but i make no promises about sticking with it if your code is a pain to work with.
