### ISSUE TITLE
Atomic swap?

### ISSUE THREAD

**Issue by SOF3** [thomcc/arcstr#30]
I would like to update an `ArcStr` atomically. Is it possible to implement some wrapper like [`arc_swap`](https://docs.rs/arc-swap/) for arcstr, or must that introduce significant overhead?

**Comment by SOF3** [comment]
It seems that we can make arcstr have an optional feature `arc-swap` that implements the [`arc_swap::RefCnt` trait](https://docs.rs/arc-swap/1.3.0/arc_swap/trait.RefCnt.html), and `ArcSwapAny<ArcStr>` can immediately work.

I can try to implement this if the proposal is approved.

**Comment by thomcc** [comment]
Yeah, that would be fine, since they seem fairly semver-stable. If there are issues I can take a stab at it as well.

**Comment by thomcc** [comment]
The feature should be called `arc_swap` though, e.g. it should just be 

```
[dependencies]
arc_swap = { version = "1", optional = true }
```

Also you should note in the docs for this feature it should mention that turning this feature on requires libstd (`arc_swap` is not `no_std`).

**Comment by SOF3** [comment]
The package name is `arc-swap` nor `arc_swap`.

**Comment by SOF3** [comment]
Sorry, it appears that arc-swap does not really support fat pointers, and using `ArcSwapAny<ArcStr>` is not really fasible.

**Comment by thomcc** [comment]
> Sorry, it appears that arc-swap does not really support fat pointers, and using ArcSwapAny<ArcStr> is not really fasible.

Hm, Worth noting that only the pointee is fat, ArcStr itself is not. But maybe they don't handle that possibility.

When I have time I'll read up on the algorithm and see if its feasible to implement a less-involved version (likely less performant too, unless the fact that we have no weak or mutable data can be leveraged) of it behind a feature or something.

**Comment by thomcc** [comment]
It's not clear that I can integrate with the ArcSwap crate. It doesn't seem so, since the pointee being fat would IIUC be a problem.

Feel free to reopen if this is mistaken.
