### ISSUE TITLE
Any chance for make_mut()?

### ISSUE THREAD

**Issue by cehteh** [thomcc/arcstr#46]
From the Docs:

* ArcStr is totally immutable. No need to lose sleep because you’re afraid of code which thinks it has a right to mutate your Arcs just because it holds the only reference…

This makes me wonder if you strongly oppose such a feature or are open to a PR which adds this (possibly feature gated).

For the time being I made my own 'cowstr' crate, but on a closer inspection it should be possible to add mutability to 'ArcStr' in a sound way.

**Comment by thomcc** [comment]
Is `&mut str` actually useful? It's not like we have a `String` (or other growable buffer) under the hood we could hand out to you.

**Comment by cehteh** [comment]
CowStr works for me (at the cost of some more complexity than ArcStr). I guess its fine to close this issue.
